from pydantic import BaseModel, Field


class LLMRequest(BaseModel):
    prompt: str = Field(..., description="The prompt input to the LLM")
    temperature: float = Field(default=0.7, description="Sampling temperature for generation")
    max_output_tokens: int = Field(default=1000, description="Maximum number of tokens to generate")

class LLMResponse(BaseModel):
    generated_text: str = Field(..., description="The text response generated by the LLM")
    prompt_tokens: int = Field(default=0, description="Number of tokens in the prompt")
    candidate_tokens: int = Field(default=0, description="Number of tokens in the generated response")
